### ISSUE TITLE
Having some difficulty with dist.go example from the docs site

### ISSUE THREAD

**Issue by aervin** [vugu/vugu#131]
**Question**
Loving the development workflow Vugu facilitates, but hit a snag when experimenting with building/distributing. Can you help us debug this build error? We've tried to follow the distribution example on the docs site as closely as possible. We're unsure if we've done something wrong, or if there's a Vugu bug.

**Additional context**
```
kenmoore|~/Projects> mkdir vugusample
kenmoore|~/Projects> vgrun --new-from-example=simple vugusample/
2020/04/24 10:03:50 Running command: [git clone -q --depth=1 https://github.com/vugu-examples/simple vugusample/]
2020/04/24 10:03:50 Removing .git directory from example
kenmoore|~/Projects> cd vugusample/
[[Copy over the dist.go file from the vugu sebsite]]
kenmoore|~/Projects/vugusample> go run dist.go 
go: finding module for package github.com/vugu/vugu/distutil
go: found github.com/vugu/vugu/distutil in github.com/vugu/vugu v0.2.3
error running: go [build -o dist/main.wasm .]; err=exit status 2; output:
# github.com/vugu-examples/simple
./0_components_vgen.go:49:8: vgn.SetInnerHTML undefined (type *vugu.VGNode has no field or method SetInnerHTML)
./0_components_vgen.go:49:22: undefined: vugu.HTML
./0_components_vgen.go:181:10: vgn.SetInnerHTML undefined (type *vugu.VGNode has no field or method SetInnerHTML)
./0_components_vgen.go:181:24: undefined: vugu.HTML
./0_components_vgen.go:198:10: vgn.SetInnerHTML undefined (type *vugu.VGNode has no field or method SetInnerHTML)
./0_components_vgen.go:198:24: undefined: vugu.HTML
panic: error running: go [build -o dist/main.wasm .]; err=exit status 2; output:
# github.com/vugu-examples/simple
./0_components_vgen.go:49:8: vgn.SetInnerHTML undefined (type *vugu.VGNode has no field or method SetInnerHTML)
./0_components_vgen.go:49:22: undefined: vugu.HTML
./0_components_vgen.go:181:10: vgn.SetInnerHTML undefined (type *vugu.VGNode has no field or method SetInnerHTML)
./0_components_vgen.go:181:24: undefined: vugu.HTML
./0_components_vgen.go:198:10: vgn.SetInnerHTML undefined (type *vugu.VGNode has no field or method SetInnerHTML)
./0_components_vgen.go:198:24: undefined: vugu.HTML
goroutine 1 [running]:
github.com/vugu/vugu/distutil.MustEnvExec(0xc00003df58, 0x2, 0x2, 0x51c6ae, 0x2, 0xc0000a2000, 0x4, 0x4, 0x0, 0x0)
        /usr/home/kenmoore/.local/go/pkg/mod/github.com/vugu/vugu@v0.2.3/distutil/exec.go:49 +0x7cb
main.main()
        /usr/home/kenmoore/Projects/vugusample/dist.go:46 +0x567
exit status 2
```

Cheers and thanks in advance!

**Comment by bradleypeabody** [comment]
This looks like a disparity between different versions.  SetInnerHTML was recently introduced only a few days ago and I believe it's only on the master branch, not in the latest release (although I will fix that very soon).

Try updating your go.mod to reference the most recent commit on master(08f71c6bf6f2921f364998aebc5907546dec8ff8 as of this message) instead of the release version and see if that resolves the issue.

**Comment by aervin** [comment]
That did it! thanks @bradleypeabody :tada:
